universe = vanilla
executable = run.sh
get_env = GRPSTAG, STAGING, USER
arguments = $(input_faa) $(train_index) $(train_labels) $(ckpt) $(outdir) $(knn)

should_transfer_files = YES
when_to_transfer_output = ON_EXIT

Requirements = (Target.HasCHTCStaging == true)

require_gpus = (DriverVersion >= 11.6) && (GlobalMemoryMB >= 50000)
request_gpus = 1

+WantGPULab = true

+GPUJobLength = "short"

request_cpus = 1
request_memory = 64GB 
request_disk = 200GB

output = $(Cluster)_$(Process).out
log = $(Cluster)_$(Process).log
error = $(Cluster)_$(Process).err

queue input_faa,train_index,train_labels,ckpt,outdir,knn from inputs.csv